/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.llanquihueTourApp.ui;
import cl.llanquihueTourApp.data.GestorEntidades;
import cl.llanquihueTourApp.model.*;

/**
 *
 * @author ADMIN
 */
public class FrmConductor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmConductor.class.getName());
   /**
    * Gestor encargado de administrar las entidades
    * registradas en el sistema.
    *
    * Se utiliza para agregar nuevos conductores y
    * generar automáticamente su identificador.
    */
    private GestorEntidades gestor;
    /**
    * Crea el formulario de registro de conductores.
    *
    * Inicializa los componentes gráficos y recibe
    * el gestor compartido donde se almacenarán las
    * entidades registradas.
    *
    * @param gestor gestor de entidades del sistema
    */
   public FrmConductor(GestorEntidades gestor) {
       initComponents();
       this.gestor = gestor;
       
   }
   
    /**
     * Limpia todos los campos del formulario.
     *
     * Se ejecuta después de registrar correctamente
     * un conductor para dejar el formulario listo
     * para un nuevo ingreso.
     */
    private void limpiarCampos() {

        ingreseNonbre.setText("");
        IngreseTelefono.setText("");
        IngreseCorreo.setText("");
        IngreseRut.setText("");
        IngreseCalle.setText("");
        IngreseCiudad.setText("");
        IngreseRegion.setText("");
        IngreseLicencia.setText("");
        IngreseCategoriaLicencia.setText("");

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        ingreseNonbre = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        IngreseTelefono = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        IngreseCorreo = new javax.swing.JTextField();
        Rut = new javax.swing.JLabel();
        IngreseRut = new javax.swing.JTextField();
        Calle = new javax.swing.JLabel();
        IngreseCalle = new javax.swing.JTextField();
        Ciudad = new javax.swing.JLabel();
        IngreseCiudad = new javax.swing.JTextField();
        Region = new javax.swing.JLabel();
        IngreseRegion = new javax.swing.JTextField();
        NumeroLicencia = new javax.swing.JLabel();
        IngreseLicencia = new javax.swing.JTextField();
        CategoriaLicencia = new javax.swing.JLabel();
        IngreseCategoriaLicencia = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Titulo1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Footer = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        VerRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("RegistrarGuia"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(55, 55, 55));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 830));

        Nombre.setBackground(new java.awt.Color(55, 55, 55));
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Nombre ");

        ingreseNonbre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ingreseNonbre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        ingreseNonbre.setPreferredSize(new java.awt.Dimension(400, 21));
        ingreseNonbre.addActionListener(this::ingreseNonbreActionPerformed);

        Telefono.setBackground(new java.awt.Color(55, 55, 55));
        Telefono.setForeground(new java.awt.Color(255, 255, 255));
        Telefono.setText("Telefono");

        IngreseTelefono.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseTelefono.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseTelefono.addActionListener(this::IngreseTelefonoActionPerformed);

        Correo.setBackground(new java.awt.Color(55, 55, 55));
        Correo.setForeground(new java.awt.Color(255, 255, 255));
        Correo.setText("Correo");

        IngreseCorreo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseCorreo.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseCorreo.addActionListener(this::IngreseCorreoActionPerformed);

        Rut.setBackground(new java.awt.Color(55, 55, 55));
        Rut.setForeground(new java.awt.Color(255, 255, 255));
        Rut.setText("Rut");

        IngreseRut.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseRut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseRut.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseRut.addActionListener(this::IngreseRutActionPerformed);

        Calle.setBackground(new java.awt.Color(55, 55, 55));
        Calle.setForeground(new java.awt.Color(255, 255, 255));
        Calle.setText("Calle");

        IngreseCalle.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseCalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseCalle.setPreferredSize(new java.awt.Dimension(400, 21));

        Ciudad.setBackground(new java.awt.Color(55, 55, 55));
        Ciudad.setForeground(new java.awt.Color(255, 255, 255));
        Ciudad.setText("Ciudad");

        IngreseCiudad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseCiudad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseCiudad.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseCiudad.addActionListener(this::IngreseCiudadActionPerformed);

        Region.setBackground(new java.awt.Color(55, 55, 55));
        Region.setForeground(new java.awt.Color(255, 255, 255));
        Region.setText("Región");

        IngreseRegion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseRegion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseRegion.setPreferredSize(new java.awt.Dimension(400, 21));

        NumeroLicencia.setBackground(new java.awt.Color(55, 55, 55));
        NumeroLicencia.setForeground(new java.awt.Color(255, 255, 255));
        NumeroLicencia.setText("Numero Licencia");

        IngreseLicencia.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseLicencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseLicencia.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseLicencia.addActionListener(this::IngreseLicenciaActionPerformed);

        CategoriaLicencia.setBackground(new java.awt.Color(55, 55, 55));
        CategoriaLicencia.setForeground(new java.awt.Color(255, 255, 255));
        CategoriaLicencia.setText("Categoria licencia");

        IngreseCategoriaLicencia.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseCategoriaLicencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseCategoriaLicencia.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseCategoriaLicencia.addActionListener(this::IngreseCategoriaLicenciaActionPerformed);

        jPanel2.setBackground(new java.awt.Color(90, 87, 87));
        jPanel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 65));

        Titulo1.setBackground(new java.awt.Color(55, 55, 55));
        Titulo1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setText("Ingrese los datos del conductor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(Titulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Titulo1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(90, 87, 87));

        Footer.setBackground(new java.awt.Color(55, 55, 55));
        Footer.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Footer.setForeground(new java.awt.Color(255, 255, 255));
        Footer.setText("LLANQUIHUE TOUR APP ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(Footer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Footer)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        BtnGuardar.setBackground(new java.awt.Color(70, 168, 61));
        BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setText("Guardar");
        BtnGuardar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnGuardar.addActionListener(this::BtnGuardarActionPerformed);

        BtnVolver.setBackground(new java.awt.Color(61, 98, 168));
        BtnVolver.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("Volver");
        BtnVolver.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnVolver.addActionListener(this::BtnVolverActionPerformed);

        VerRegistro.setBackground(new java.awt.Color(255, 0, 0));
        VerRegistro.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        VerRegistro.setForeground(new java.awt.Color(255, 255, 255));
        VerRegistro.setText("Ver registro");
        VerRegistro.setMaximumSize(new java.awt.Dimension(100, 30));
        VerRegistro.setMinimumSize(new java.awt.Dimension(100, 30));
        VerRegistro.setPreferredSize(new java.awt.Dimension(100, 30));
        VerRegistro.addActionListener(this::VerRegistroActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CategoriaLicencia)
                    .addComponent(NumeroLicencia)
                    .addComponent(IngreseLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Region)
                    .addComponent(IngreseRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ciudad)
                    .addComponent(IngreseCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calle)
                    .addComponent(IngreseCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rut)
                    .addComponent(IngreseRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correo)
                    .addComponent(IngreseCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefono)
                    .addComponent(IngreseTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre)
                    .addComponent(ingreseNonbre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(VerRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(IngreseCategoriaLicencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingreseNonbre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Telefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Correo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Rut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseRut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Calle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ciudad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Region)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NumeroLicencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(CategoriaLicencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseCategoriaLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VerRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngreseCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseCorreoActionPerformed

    private void IngreseRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseRutActionPerformed

    private void IngreseCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseCiudadActionPerformed

    private void IngreseLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseLicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseLicenciaActionPerformed

    private void IngreseTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseTelefonoActionPerformed

    private void IngreseCategoriaLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseCategoriaLicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseCategoriaLicenciaActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        
   try {

        Direccion direccion = new Direccion(
                IngreseCalle.getText(),
                IngreseCiudad.getText(),
                IngreseRegion.getText()
        );


        Rut rut = new Rut(
                IngreseRut.getText()
        );

  
    
                Conductor conductor = new Conductor(
        gestor.generarNuevoId(),
                ingreseNonbre.getText(),
                IngreseTelefono.getText(),
                IngreseCorreo.getText(),
                direccion,
                rut,
                IngreseLicencia.getText(),
                IngreseCategoriaLicencia.getText()
        );


        gestor.agregarEntidad(conductor);


        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Conductor registrado correctamente"
        );


        limpiarCampos();


    } catch(Exception e){

        javax.swing.JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );

    }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void ingreseNonbreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreseNonbreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingreseNonbreActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
         this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void VerRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerRegistroActionPerformed
        FrmMostrarEntidades ventana = new FrmMostrarEntidades(gestor);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_VerRegistroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel Calle;
    private javax.swing.JLabel CategoriaLicencia;
    private javax.swing.JLabel Ciudad;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Footer;
    private javax.swing.JTextField IngreseCalle;
    private javax.swing.JTextField IngreseCategoriaLicencia;
    private javax.swing.JTextField IngreseCiudad;
    private javax.swing.JTextField IngreseCorreo;
    private javax.swing.JTextField IngreseLicencia;
    private javax.swing.JTextField IngreseRegion;
    private javax.swing.JTextField IngreseRut;
    private javax.swing.JTextField IngreseTelefono;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NumeroLicencia;
    private javax.swing.JLabel Region;
    private javax.swing.JLabel Rut;
    private javax.swing.JLabel Telefono;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JButton VerRegistro;
    private javax.swing.JTextField ingreseNonbre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
