/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.llanquihueTourApp.ui;
import cl.llanquihueTourApp.data.GestorEntidades;

/**
 *
 * @author ADMIN
 */
public class FrmFront extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmFront.class.getName());
/**
 * Gestor central de entidades registradas en el sistema.
 *
 * Se comparte entre los distintos formularios para
 * almacenar y administrar las entidades creadas
 * durante la ejecución de la aplicación.
 */
private GestorEntidades gestor;

/**
 * Constructor del formulario principal.
 *
 * Inicializa los componentes gráficos y crea una
 * única instancia de GestorEntidades, la cual será
 * compartida con los demás formularios para registrar
 * y consultar las entidades del sistema.
 */
public FrmFront() {

    initComponents();

    gestor = new GestorEntidades();

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegistrarConductor = new javax.swing.JButton();
        MostarInformacion = new javax.swing.JButton();
        RegistrarServicioTuristico = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        RegistrarGuia = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Slogan1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Slogan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistrarConductor.setText("Registrar Conductor");
        RegistrarConductor.addActionListener(this::RegistrarConductorActionPerformed);
        jPanel1.add(RegistrarConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 310, 60));

        MostarInformacion.setText("Mostrar Información");
        MostarInformacion.addActionListener(this::MostarInformacionActionPerformed);
        jPanel1.add(MostarInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 310, 60));

        RegistrarServicioTuristico.setText("Registrar servicio turistico");
        RegistrarServicioTuristico.addActionListener(this::RegistrarServicioTuristicoActionPerformed);
        jPanel1.add(RegistrarServicioTuristico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 310, 60));

        Salir.setText("Salir");
        Salir.addActionListener(this::SalirActionPerformed);
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, 310, 60));

        RegistrarGuia.setText("Registrar Guia");
        RegistrarGuia.addActionListener(this::RegistrarGuiaActionPerformed);
        jPanel1.add(RegistrarGuia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 310, 60));

        jButton1.setText("Registrar capitan");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 310, 60));

        Slogan1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        Slogan1.setForeground(new java.awt.Color(255, 255, 255));
        Slogan1.setText("Registrete y se parte de nuestra empresa");
        jPanel1.add(Slogan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 390, -1));

        jPanel2.setBackground(new java.awt.Color(90, 87, 87));

        Slogan.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Slogan.setForeground(new java.awt.Color(255, 255, 255));
        Slogan.setText("Llanquihue Tour Todos los derechos resevados 2026");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(Slogan)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Slogan)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 550, 90));

        jPanel3.setBackground(new java.awt.Color(90, 87, 87));
        jPanel3.setPreferredSize(new java.awt.Dimension(550, 60));

        Titulo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("LLANQUIHUE TOUR APP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(Titulo)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Titulo)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 560, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/**
 * Abre el formulario de registro de conductores.
 *
 * @param evt evento generado al presionar el botón
**
 * Muestra todas las entidades registradas en el sistema.
 *
 * @param evt evento generado al presionar el botón
 */
    private void MostarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostarInformacionActionPerformed
        FrmMostrarEntidades ventana = new FrmMostrarEntidades(gestor);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_MostarInformacionActionPerformed

    private void RegistrarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarConductorActionPerformed
        FrmConductor ventana = new FrmConductor(gestor);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_RegistrarConductorActionPerformed

    private void RegistrarServicioTuristicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarServicioTuristicoActionPerformed
          FrmServicioTuristico ventana =
            new FrmServicioTuristico(gestor);

    ventana.setLocationRelativeTo(null);
    ventana.setVisible(true);
    }//GEN-LAST:event_RegistrarServicioTuristicoActionPerformed

    private void RegistrarGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarGuiaActionPerformed
        FrmGuia ventana = new FrmGuia(gestor);
    ventana.setLocationRelativeTo(null);
    ventana.setVisible(true);
    }//GEN-LAST:event_RegistrarGuiaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           FrmCapitanNave ventana = new FrmCapitanNave(gestor);
    ventana.setLocationRelativeTo(null);
    ventana.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
           int opcion = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Desea salir de la aplicación?",
            "Confirmar salida",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (opcion == javax.swing.JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_SalirActionPerformed
   
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MostarInformacion;
    private javax.swing.JButton RegistrarConductor;
    private javax.swing.JButton RegistrarGuia;
    private javax.swing.JButton RegistrarServicioTuristico;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Slogan;
    private javax.swing.JLabel Slogan1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
