/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.llanquihueTourApp.ui;
import cl.llanquihueTourApp.data.GestorEntidades;
/**
 *
 * @author ADMIN
 */
public class FrmMostrarEntidades extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMostrarEntidades.class.getName());
private GestorEntidades gestor;
    /**
     * Creates new form FrmMostrarEntidades
     */
    public FrmMostrarEntidades(GestorEntidades gestor) {
        initComponents();
        this.gestor = gestor;
        txtMostrar.setText(gestor.mostrarEntidades());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        PaneTitulo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        TituloFooter = new javax.swing.JLabel();
        BtnLimpiarRegistro = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Container.setBackground(new java.awt.Color(55, 55, 55));
        Container.setPreferredSize(new java.awt.Dimension(550, 830));

        PaneTitulo.setBackground(new java.awt.Color(90, 87, 87));

        Titulo.setBackground(new java.awt.Color(55, 55, 55));
        Titulo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("REGISTROS LLANQUIHUE TOUR");

        javax.swing.GroupLayout PaneTituloLayout = new javax.swing.GroupLayout(PaneTitulo);
        PaneTitulo.setLayout(PaneTituloLayout);
        PaneTituloLayout.setHorizontalGroup(
            PaneTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(PaneTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PaneTituloLayout.createSequentialGroup()
                    .addGap(110, 110, 110)
                    .addComponent(Titulo)
                    .addContainerGap(110, Short.MAX_VALUE)))
        );
        PaneTituloLayout.setVerticalGroup(
            PaneTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
            .addGroup(PaneTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PaneTituloLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(Titulo)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        Footer.setBackground(new java.awt.Color(90, 87, 87));

        TituloFooter.setBackground(new java.awt.Color(55, 55, 55));
        TituloFooter.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        TituloFooter.setForeground(new java.awt.Color(255, 255, 255));
        TituloFooter.setText("LLANQUIHUE TOUR APP");

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TituloFooter)
                .addGap(113, 113, 113))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TituloFooter)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        BtnLimpiarRegistro.setBackground(new java.awt.Color(70, 168, 61));
        BtnLimpiarRegistro.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BtnLimpiarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        BtnLimpiarRegistro.setText("Limpiar");
        BtnLimpiarRegistro.setActionCommand("Limpiar ");
        BtnLimpiarRegistro.setMaximumSize(new java.awt.Dimension(113, 30));
        BtnLimpiarRegistro.setMinimumSize(new java.awt.Dimension(113, 30));
        BtnLimpiarRegistro.setPreferredSize(new java.awt.Dimension(113, 30));
        BtnLimpiarRegistro.addActionListener(this::BtnLimpiarRegistroActionPerformed);

        BtnVolver.setBackground(new java.awt.Color(61, 98, 168));
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("Volver");
        BtnVolver.setPreferredSize(new java.awt.Dimension(113, 30));
        BtnVolver.addActionListener(this::BtnVolverActionPerformed);

        txtMostrar.setColumns(20);
        txtMostrar.setRows(5);
        jScrollPane1.setViewportView(txtMostrar);

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaneTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerLayout.createSequentialGroup()
                        .addComponent(BtnLimpiarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addComponent(PaneTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpiarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(Footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
           this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnLimpiarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarRegistroActionPerformed
          int respuesta = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro que desea eliminar todos los registros?",
            "Confirmar limpieza",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {

        gestor.limpiarEntidades();

        txtMostrar.setText("");

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Registros eliminados correctamente"
        );

    }

    }//GEN-LAST:event_BtnLimpiarRegistroActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLimpiarRegistro;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JPanel Container;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel PaneTitulo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloFooter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtMostrar;
    // End of variables declaration//GEN-END:variables
}
