/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.llanquihueTourApp.ui;
import cl.llanquihueTourApp.data.GestorEntidades;
import cl.llanquihueTourApp.model.*;
 
/**
 *
 * @author ADMIN
 */
public class FrmServicioTuristico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmServicioTuristico.class.getName());

      /**
    * Gestor encargado de administrar las entidades
    * registradas en el sistema.
    *
    * Se utiliza para agregar nuevos conductores y
    * generar automáticamente su identificador.
    */
    private GestorEntidades gestor;
    /**
    * Crea el formulario de registro de conductores.
    *
    * Inicializa los componentes gráficos y recibe
    * el gestor compartido donde se almacenarán las
    * entidades registradas.
    *
    * @param gestor gestor de entidades del sistema
    */
   public FrmServicioTuristico(GestorEntidades gestor) {
       initComponents();

    this.gestor = gestor;


    CmbTipoServicio.removeAllItems();


    CmbTipoServicio.addItem("Paseo Lacustre");
    CmbTipoServicio.addItem("Ruta Gastronómica");
    CmbTipoServicio.addItem("Excursión Cultural");


    CmbTipoServicio.setSelectedIndex(0);


    actualizarCampos();
       
   }
   private void actualizarCampos() {

  if (CmbTipoServicio.getSelectedItem() == null) {
        return;
    }

    String tipo = CmbTipoServicio.getSelectedItem().toString();

    switch (tipo) {

        case "Paseo Lacustre":

            lblDato1.setText("Lago");
            lblDato2.setText("Tipo de recorrido");
            lblDato3.setText("Tipo de embarcación");

            break;


        case "Ruta Gastronómica":

            lblDato1.setText("Restaurante");
            lblDato2.setText("Tipo gastronomía");
            lblDato3.setText("Cantidad de paradas");

            break;


        case "Excursión Cultural":

            lblDato1.setText("Lugar cultural");
            lblDato2.setText("Tipo patrimonio");
            lblDato3.setText("Entrada incluida");

            break;
    }
}
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        IngreseNombre = new javax.swing.JTextField();
        Descripcion = new javax.swing.JLabel();
        IngreseDescripcion = new javax.swing.JTextField();
        Duracion = new javax.swing.JLabel();
        IngreseDuracion = new javax.swing.JTextField();
        Precio = new javax.swing.JLabel();
        IngresePrecio = new javax.swing.JTextField();
        TipoServicio = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        VerRegistro = new javax.swing.JButton();
        CmbTipoServicio = new javax.swing.JComboBox<>();
        lblDato1 = new javax.swing.JLabel();
        TxtDato1 = new javax.swing.JTextField();
        lblDato2 = new javax.swing.JLabel();
        TxtDato2 = new javax.swing.JTextField();
        lblDato3 = new javax.swing.JLabel();
        TxtDato3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        IngreseGuia = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        Titulo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Titulo.setText("REGISTRAR SERVICIO TURISTICO");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(103, 103, 103))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Titulo)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setText("LLANQUIHUE TOUR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        Nombre.setText("Nombre");

        IngreseNombre.addActionListener(this::IngreseNombreActionPerformed);

        Descripcion.setText("Descripción");

        IngreseDescripcion.addActionListener(this::IngreseDescripcionActionPerformed);

        Duracion.setText("Duracion");

        IngreseDuracion.addActionListener(this::IngreseDuracionActionPerformed);

        Precio.setText("Precio");

        IngresePrecio.addActionListener(this::IngresePrecioActionPerformed);

        TipoServicio.setText("Tipo de servicio");

        Guardar.setText("Guardar");
        Guardar.addActionListener(this::GuardarActionPerformed);

        Volver.setText("Volver");
        Volver.addActionListener(this::VolverActionPerformed);

        VerRegistro.setText("Ver registro");
        VerRegistro.addActionListener(this::VerRegistroActionPerformed);

        CmbTipoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbTipoServicio.addActionListener(this::CmbTipoServicioActionPerformed);

        lblDato1.setText("Dato1");

        TxtDato1.addActionListener(this::TxtDato1ActionPerformed);

        lblDato2.setText("Dato 2");

        TxtDato2.addActionListener(this::TxtDato2ActionPerformed);

        lblDato3.setText("Dato 3");

        TxtDato3.addActionListener(this::TxtDato3ActionPerformed);

        jLabel2.setText("Guia");

        IngreseGuia.addActionListener(this::IngreseGuiaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(Duracion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDato3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblDato2)
                                .addComponent(Descripcion)
                                .addComponent(Nombre)
                                .addComponent(IngreseNombre)
                                .addComponent(IngreseDescripcion)
                                .addComponent(IngreseDuracion)
                                .addComponent(IngresePrecio)
                                .addComponent(CmbTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Guardar)
                                    .addGap(38, 38, 38)
                                    .addComponent(Volver)
                                    .addGap(62, 62, 62)
                                    .addComponent(VerRegistro))
                                .addComponent(TxtDato1)
                                .addComponent(TxtDato2)
                                .addComponent(Precio)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(lblDato1))
                                .addComponent(IngreseGuia, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
                            .addComponent(TxtDato3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(TipoServicio))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IngreseNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Descripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IngreseDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Duracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IngreseDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Precio)
                .addGap(2, 2, 2)
                .addComponent(IngresePrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(TipoServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CmbTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDato1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDato2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDato3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TxtDato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Volver)
                    .addComponent(VerRegistro))
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngreseNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseNombreActionPerformed

    private void IngreseDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseDescripcionActionPerformed

    private void IngreseDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseDuracionActionPerformed

    private void IngresePrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresePrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresePrecioActionPerformed

    private void CmbTipoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbTipoServicioActionPerformed
           actualizarCampos();
    }//GEN-LAST:event_CmbTipoServicioActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
             
  try {

        int id = gestor.generarNuevoId();

        String nombre = IngreseNombre.getText();
        String descripcion = IngreseDescripcion.getText();
        String duracion = IngreseDuracion.getText();
        double precio = Double.parseDouble(IngresePrecio.getText());

        String lago = TxtDato1.getText();
        String recorrido = TxtDato2.getText();
        String embarcacion = TxtDato3.getText();

        // FALTA obtener un guía y un transporte
        Guia guia = null;
        Transporte transporte = null;

        PaseoLacustre paseo = new PaseoLacustre(
                id,
                nombre,
                descripcion,
                duracion,
                precio,
                guia,
                transporte,
                lago,
                recorrido,
                embarcacion
        );

        gestor.agregarEntidad(paseo);

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Servicio registrado correctamente."
        );

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );

    }
    }//GEN-LAST:event_GuardarActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
         this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void VerRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerRegistroActionPerformed
          FrmMostrarEntidades ventana = new FrmMostrarEntidades(gestor);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_VerRegistroActionPerformed

    private void TxtDato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDato1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDato1ActionPerformed

    private void TxtDato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDato2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDato2ActionPerformed

    private void TxtDato3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDato3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDato3ActionPerformed

    private void IngreseGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseGuiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseGuiaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbTipoServicio;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Duracion;
    private javax.swing.JButton Guardar;
    private javax.swing.JPanel Header;
    private javax.swing.JTextField IngreseDescripcion;
    private javax.swing.JTextField IngreseDuracion;
    private javax.swing.JTextField IngreseGuia;
    private javax.swing.JTextField IngreseNombre;
    private javax.swing.JTextField IngresePrecio;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel TipoServicio;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField TxtDato1;
    private javax.swing.JTextField TxtDato2;
    private javax.swing.JTextField TxtDato3;
    private javax.swing.JButton VerRegistro;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblDato1;
    private javax.swing.JLabel lblDato2;
    private javax.swing.JLabel lblDato3;
    // End of variables declaration//GEN-END:variables
}
