/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.llanquihueTourApp.ui;
import cl.llanquihueTourApp.data.GestorEntidades;
import cl.llanquihueTourApp.util.Validator;
import cl.llanquihueTourApp.model.*;
import java.awt.Component;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
/**
 *
 * @author ADMIN
 */
public class FrmAutomovil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAutomovil.class.getName());
   /**
    * Gestor encargado de administrar las entidades
    * registradas en el sistema.
    *
    * Se utiliza para agregar nuevos conductores y
    * generar automáticamente su identificador.
    */
    private GestorEntidades gestor;
    /**
    * Crea el formulario de registro de conductores.
    *
    * Inicializa los componentes gráficos y recibe
    * el gestor compartido donde se almacenarán las
    * entidades registradas.
    *
    * @param gestor gestor de entidades del sistema
    */
    public FrmAutomovil(GestorEntidades gestor) {
       initComponents();
       this.gestor = gestor;

       cargarConductores();

       cboConductor.setRenderer(new DefaultListCellRenderer() {

           @Override
           public Component getListCellRendererComponent(
                   JList<?> list,
                   Object value,
                   int index,
                   boolean isSelected,
                   boolean cellHasFocus) {

               super.getListCellRendererComponent(
                       list,
                       value,
                       index,
                       isSelected,
                       cellHasFocus);

               if (value instanceof Conductor conductor) {
                   setText(conductor.getNombre());
               }

               return this;
           }
       });

   }
   
   private void cargarConductores() {

        cboConductor.removeAllItems();

        for (Registrable r : gestor.getEntidades()) {

            if (r instanceof Conductor conductor) {

                cboConductor.addItem(conductor);

            }

        }

    }
    /**
     * Limpia todos los campos del formulario.
     *
     * Se ejecuta después de registrar correctamente
     * un conductor para dejar el formulario listo
     * para un nuevo ingreso.
     */
    private void limpiarCampos() {

        ingreseIdentificador.setText("");
        IngreseCapacidad.setText("");
        IngreseEstado.setText("");
  
        IngreseMarca.setText("");
        IngreseModelo.setText("");
        IngreseAnio.setText("");
   

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        identificador = new javax.swing.JLabel();
        ingreseIdentificador = new javax.swing.JTextField();
        Capacidad = new javax.swing.JLabel();
        IngreseCapacidad = new javax.swing.JTextField();
        estado = new javax.swing.JLabel();
        IngreseEstado = new javax.swing.JTextField();
        responsable = new javax.swing.JLabel();
        marca = new javax.swing.JLabel();
        IngreseMarca = new javax.swing.JTextField();
        modelo = new javax.swing.JLabel();
        IngreseModelo = new javax.swing.JTextField();
        anio = new javax.swing.JLabel();
        IngreseAnio = new javax.swing.JTextField();
        header = new javax.swing.JPanel();
        Titulo1 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        Footer = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        BtnVerRegistro = new javax.swing.JButton();
        cboConductor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("RegistrarGuia"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(55, 55, 55));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 830));

        identificador.setBackground(new java.awt.Color(55, 55, 55));
        identificador.setForeground(new java.awt.Color(255, 255, 255));
        identificador.setText("Identificador (patente)");

        ingreseIdentificador.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ingreseIdentificador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        ingreseIdentificador.setPreferredSize(new java.awt.Dimension(400, 21));
        ingreseIdentificador.addActionListener(this::ingreseIdentificadorActionPerformed);

        Capacidad.setBackground(new java.awt.Color(55, 55, 55));
        Capacidad.setForeground(new java.awt.Color(255, 255, 255));
        Capacidad.setText("Capacidad");

        IngreseCapacidad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseCapacidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseCapacidad.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseCapacidad.addActionListener(this::IngreseCapacidadActionPerformed);

        estado.setBackground(new java.awt.Color(55, 55, 55));
        estado.setForeground(new java.awt.Color(255, 255, 255));
        estado.setText("Estado");

        IngreseEstado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseEstado.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseEstado.addActionListener(this::IngreseEstadoActionPerformed);

        responsable.setBackground(new java.awt.Color(55, 55, 55));
        responsable.setForeground(new java.awt.Color(255, 255, 255));
        responsable.setText("Responsable");

        marca.setBackground(new java.awt.Color(55, 55, 55));
        marca.setForeground(new java.awt.Color(255, 255, 255));
        marca.setText("Marca");

        IngreseMarca.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseMarca.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseMarca.addActionListener(this::IngreseMarcaActionPerformed);

        modelo.setBackground(new java.awt.Color(55, 55, 55));
        modelo.setForeground(new java.awt.Color(255, 255, 255));
        modelo.setText("Modelo");

        IngreseModelo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseModelo.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseModelo.addActionListener(this::IngreseModeloActionPerformed);

        anio.setBackground(new java.awt.Color(55, 55, 55));
        anio.setForeground(new java.awt.Color(255, 255, 255));
        anio.setText("Añio");

        IngreseAnio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseAnio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseAnio.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseAnio.addActionListener(this::IngreseAnioActionPerformed);

        header.setBackground(new java.awt.Color(90, 87, 87));
        header.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        header.setPreferredSize(new java.awt.Dimension(450, 65));

        Titulo1.setBackground(new java.awt.Color(55, 55, 55));
        Titulo1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setText("Ingrese los datos del automovil");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(Titulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Titulo1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        footer.setBackground(new java.awt.Color(90, 87, 87));

        Footer.setBackground(new java.awt.Color(55, 55, 55));
        Footer.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Footer.setForeground(new java.awt.Color(255, 255, 255));
        Footer.setText("LLANQUIHUE TOUR APP ");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(Footer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Footer)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        BtnGuardar.setBackground(new java.awt.Color(70, 168, 61));
        BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setText("Guardar");
        BtnGuardar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnGuardar.addActionListener(this::BtnGuardarActionPerformed);

        BtnVolver.setBackground(new java.awt.Color(61, 98, 168));
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("Volver");
        BtnVolver.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnVolver.addActionListener(this::BtnVolverActionPerformed);

        BtnVerRegistro.setBackground(new java.awt.Color(255, 0, 0));
        BtnVerRegistro.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BtnVerRegistro.setForeground(new java.awt.Color(255, 255, 255));
        BtnVerRegistro.setText("Ver registro");
        BtnVerRegistro.setMaximumSize(new java.awt.Dimension(100, 30));
        BtnVerRegistro.setMinimumSize(new java.awt.Dimension(100, 30));
        BtnVerRegistro.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnVerRegistro.addActionListener(this::BtnVerRegistroActionPerformed);

        cboConductor.addActionListener(this::cboConductorActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
            .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(anio)
                    .addComponent(modelo)
                    .addComponent(IngreseModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(marca)
                    .addComponent(IngreseMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(responsable)
                    .addComponent(estado)
                    .addComponent(IngreseEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Capacidad)
                    .addComponent(IngreseCapacidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(identificador)
                    .addComponent(ingreseIdentificador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnVerRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(IngreseAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboConductor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(identificador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingreseIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Capacidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(estado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(responsable)
                .addGap(13, 13, 13)
                .addComponent(cboConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(marca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(anio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVerRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVerRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerRegistroActionPerformed
        FrmMostrarEntidades ventana = new FrmMostrarEntidades(gestor);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_BtnVerRegistroActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
            try {

        Conductor conductor =
                (Conductor) cboConductor.getSelectedItem();

        if (conductor == null) {
            throw new IllegalArgumentException(
                    "Debe seleccionar un conductor.");
        }

        int capacidad =
                Integer.parseInt(IngreseCapacidad.getText());

        int anio =
                Integer.parseInt(IngreseAnio.getText());

        if (!Validator.validarIdentificador(
                ingreseIdentificador.getText())) {

            throw new IllegalArgumentException(
                    "Identificador inválido.");
        }

        if (!Validator.validarCapacidad(capacidad)) {

            throw new IllegalArgumentException(
                    "Capacidad inválida.");
        }

        if (!Validator.validarEstado(
                IngreseEstado.getText())) {

            throw new IllegalArgumentException(
                    "Estado inválido.");
        }

        if (!Validator.validarMarca(
                IngreseMarca.getText())) {

            throw new IllegalArgumentException(
                    "Marca inválida.");
        }

        if (!Validator.validarModelo(
                IngreseModelo.getText())) {

            throw new IllegalArgumentException(
                    "Modelo inválido.");
        }

        if (!Validator.validarAnio(anio)) {

            throw new IllegalArgumentException(
                    "Año inválido.");
        }

        Automovil automovil =
                new Automovil(
                        gestor.generarNuevoId(),
                        ingreseIdentificador.getText(),
                        capacidad,
                        IngreseEstado.getText(),
                        conductor,
                        IngreseMarca.getText(),
                        IngreseModelo.getText(),
                        anio
                );

        gestor.agregarEntidad(automovil);

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Automóvil registrado correctamente.");

        limpiarCampos();

    } catch (NumberFormatException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Capacidad y año deben ser numéricos.");

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                e.getMessage());

    }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void IngreseModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseModeloActionPerformed

    private void IngreseEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseEstadoActionPerformed

    private void IngreseCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseCapacidadActionPerformed

    private void ingreseIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreseIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingreseIdentificadorActionPerformed

    private void IngreseAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseAnioActionPerformed

    private void IngreseMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseMarcaActionPerformed

    private void cboConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboConductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboConductorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnVerRegistro;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel Capacidad;
    private javax.swing.JLabel Footer;
    private javax.swing.JTextField IngreseAnio;
    private javax.swing.JTextField IngreseCapacidad;
    private javax.swing.JTextField IngreseEstado;
    private javax.swing.JTextField IngreseMarca;
    private javax.swing.JTextField IngreseModelo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel anio;
    private javax.swing.JComboBox<Conductor> cboConductor;
    private javax.swing.JLabel estado;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel identificador;
    private javax.swing.JTextField ingreseIdentificador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel marca;
    private javax.swing.JLabel modelo;
    private javax.swing.JLabel responsable;
    // End of variables declaration//GEN-END:variables
}
