/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.llanquihueTourApp.ui;
import cl.llanquihueTourApp.data.GestorEntidades;
import cl.llanquihueTourApp.model.*;

/**
 *
 * @author ADMIN
 */
public class FrmCapitanNave extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCapitanNave.class.getName());
   /**
    * Gestor encargado de administrar las entidades
    * registradas en el sistema.
    *
    * Se utiliza para agregar nuevos conductores y
    * generar automáticamente su identificador.
    */
    private GestorEntidades gestor;
    /**
    * Crea el formulario de registro de conductores.
    *
    * Inicializa los componentes gráficos y recibe
    * el gestor compartido donde se almacenarán las
    * entidades registradas.
    *
    * @param gestor gestor de entidades del sistema
    */
   public FrmCapitanNave(GestorEntidades gestor) {
       initComponents();
       this.gestor = gestor;
       
   }
   
    /**
     * Limpia todos los campos del formulario.
     *
     * Se ejecuta después de registrar correctamente
     * un conductor para dejar el formulario listo
     * para un nuevo ingreso.
     */
    private void limpiarCampos() {

        ingreseNonbre.setText("");
        IngreseTelefono.setText("");
        IngreseCorreo.setText("");
        IngreseRut.setText("");
        IngreseCalle.setText("");
        IngreseCiudad.setText("");
        IngreseRegion.setText("");
        IngreseLicenciaNautica.setText("");
        IngreseCategoriaLicenciaNautica.setText("");

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        ingreseNonbre = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        IngreseTelefono = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        IngreseCorreo = new javax.swing.JTextField();
        Rut = new javax.swing.JLabel();
        IngreseRut = new javax.swing.JTextField();
        Calle = new javax.swing.JLabel();
        IngreseCalle = new javax.swing.JTextField();
        Ciudad = new javax.swing.JLabel();
        IngreseCiudad = new javax.swing.JTextField();
        Region = new javax.swing.JLabel();
        IngreseRegion = new javax.swing.JTextField();
        LicenciaNautica = new javax.swing.JLabel();
        IngreseLicenciaNautica = new javax.swing.JTextField();
        CategoriaLicenciaNautica = new javax.swing.JLabel();
        IngreseCategoriaLicenciaNautica = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Titulo1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Footer = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("RegistrarGuia"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(55, 55, 55));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 830));

        Nombre.setBackground(new java.awt.Color(55, 55, 55));
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Nombre ");

        ingreseNonbre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ingreseNonbre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        ingreseNonbre.setPreferredSize(new java.awt.Dimension(400, 21));
        ingreseNonbre.addActionListener(this::ingreseNonbreActionPerformed);

        Telefono.setBackground(new java.awt.Color(55, 55, 55));
        Telefono.setForeground(new java.awt.Color(255, 255, 255));
        Telefono.setText("Telefono");

        IngreseTelefono.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseTelefono.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseTelefono.addActionListener(this::IngreseTelefonoActionPerformed);

        Correo.setBackground(new java.awt.Color(55, 55, 55));
        Correo.setForeground(new java.awt.Color(255, 255, 255));
        Correo.setText("Correo");

        IngreseCorreo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseCorreo.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseCorreo.addActionListener(this::IngreseCorreoActionPerformed);

        Rut.setBackground(new java.awt.Color(55, 55, 55));
        Rut.setForeground(new java.awt.Color(255, 255, 255));
        Rut.setText("Rut");

        IngreseRut.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseRut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseRut.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseRut.addActionListener(this::IngreseRutActionPerformed);

        Calle.setBackground(new java.awt.Color(55, 55, 55));
        Calle.setForeground(new java.awt.Color(255, 255, 255));
        Calle.setText("Calle");

        IngreseCalle.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseCalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseCalle.setPreferredSize(new java.awt.Dimension(400, 21));

        Ciudad.setBackground(new java.awt.Color(55, 55, 55));
        Ciudad.setForeground(new java.awt.Color(255, 255, 255));
        Ciudad.setText("Ciudad");

        IngreseCiudad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseCiudad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseCiudad.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseCiudad.addActionListener(this::IngreseCiudadActionPerformed);

        Region.setBackground(new java.awt.Color(55, 55, 55));
        Region.setForeground(new java.awt.Color(255, 255, 255));
        Region.setText("Región");

        IngreseRegion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseRegion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseRegion.setPreferredSize(new java.awt.Dimension(400, 21));

        LicenciaNautica.setBackground(new java.awt.Color(55, 55, 55));
        LicenciaNautica.setForeground(new java.awt.Color(255, 255, 255));
        LicenciaNautica.setText("Licencia nautica");

        IngreseLicenciaNautica.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseLicenciaNautica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseLicenciaNautica.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseLicenciaNautica.addActionListener(this::IngreseLicenciaNauticaActionPerformed);

        CategoriaLicenciaNautica.setBackground(new java.awt.Color(55, 55, 55));
        CategoriaLicenciaNautica.setForeground(new java.awt.Color(255, 255, 255));
        CategoriaLicenciaNautica.setText("Categoria licencia nautica");

        IngreseCategoriaLicenciaNautica.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseCategoriaLicenciaNautica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseCategoriaLicenciaNautica.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseCategoriaLicenciaNautica.addActionListener(this::IngreseCategoriaLicenciaNauticaActionPerformed);

        jPanel2.setBackground(new java.awt.Color(90, 87, 87));
        jPanel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 65));

        Titulo1.setBackground(new java.awt.Color(55, 55, 55));
        Titulo1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setText("Ingrese los datos del capitan de la nave");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(Titulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Titulo1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(90, 87, 87));

        Footer.setBackground(new java.awt.Color(55, 55, 55));
        Footer.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Footer.setForeground(new java.awt.Color(255, 255, 255));
        Footer.setText("LLANQUIHUE TOUR APP ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(Footer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Footer)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        BtnGuardar.setBackground(new java.awt.Color(70, 168, 61));
        BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setText("Guardar");
        BtnGuardar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnGuardar.addActionListener(this::BtnGuardarActionPerformed);

        BtnVolver.setBackground(new java.awt.Color(61, 98, 168));
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("Volver");
        BtnVolver.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnVolver.addActionListener(this::BtnVolverActionPerformed);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ver registro");
        jButton1.setMaximumSize(new java.awt.Dimension(100, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CategoriaLicenciaNautica)
                    .addComponent(LicenciaNautica)
                    .addComponent(IngreseLicenciaNautica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Region)
                    .addComponent(IngreseRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ciudad)
                    .addComponent(IngreseCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calle)
                    .addComponent(IngreseCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rut)
                    .addComponent(IngreseRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correo)
                    .addComponent(IngreseCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefono)
                    .addComponent(IngreseTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre)
                    .addComponent(ingreseNonbre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(IngreseCategoriaLicenciaNautica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingreseNonbre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Telefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Correo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Rut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseRut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Calle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ciudad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Region)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LicenciaNautica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseLicenciaNautica, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(CategoriaLicenciaNautica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseCategoriaLicenciaNautica, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngreseCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseCorreoActionPerformed

    private void IngreseRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseRutActionPerformed

    private void IngreseCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseCiudadActionPerformed

    private void IngreseLicenciaNauticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseLicenciaNauticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseLicenciaNauticaActionPerformed

    private void IngreseTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseTelefonoActionPerformed

    private void IngreseCategoriaLicenciaNauticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseCategoriaLicenciaNauticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseCategoriaLicenciaNauticaActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        
   try {

        Direccion direccion = new Direccion(
                IngreseCalle.getText(),
                IngreseCiudad.getText(),
                IngreseRegion.getText()
        );


        Rut rut = new Rut(
                IngreseRut.getText()
        );

  
    
                CapitanNave capitan = new CapitanNave(
        gestor.generarNuevoId(),
                ingreseNonbre.getText(),
                IngreseTelefono.getText(),
                IngreseCorreo.getText(),
                direccion,
                rut,
                IngreseLicenciaNautica.getText(),
                IngreseCategoriaLicenciaNautica.getText()
        );


        gestor.agregarEntidad(capitan);


        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Capitan de la nave registrado correctamente"
        );


        limpiarCampos();


    } catch(Exception e){

        javax.swing.JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );

    }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void ingreseNonbreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreseNonbreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingreseNonbreActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
         this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmMostrarEntidades ventana = new FrmMostrarEntidades(gestor);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel Calle;
    private javax.swing.JLabel CategoriaLicenciaNautica;
    private javax.swing.JLabel Ciudad;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Footer;
    private javax.swing.JTextField IngreseCalle;
    private javax.swing.JTextField IngreseCategoriaLicenciaNautica;
    private javax.swing.JTextField IngreseCiudad;
    private javax.swing.JTextField IngreseCorreo;
    private javax.swing.JTextField IngreseLicenciaNautica;
    private javax.swing.JTextField IngreseRegion;
    private javax.swing.JTextField IngreseRut;
    private javax.swing.JTextField IngreseTelefono;
    private javax.swing.JLabel LicenciaNautica;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Region;
    private javax.swing.JLabel Rut;
    private javax.swing.JLabel Telefono;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JTextField ingreseNonbre;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
