/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.llanquihueTourApp.ui;
import cl.llanquihueTourApp.data.GestorEntidades;
import cl.llanquihueTourApp.util.Validator;
import cl.llanquihueTourApp.model.*;
import java.awt.Component;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
/**
 *
 * @author ADMIN
 */
public class FrmEmbarcacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEmbarcacion.class.getName());
   /**
    * Gestor encargado de administrar las entidades
    * registradas en el sistema.
    *
    * Se utiliza para agregar nuevos conductores y
    * generar automáticamente su identificador.
    */
    private GestorEntidades gestor;
    /**
    * Crea el formulario de registro de conductores.
    *
    * Inicializa los componentes gráficos y recibe
    * el gestor compartido donde se almacenarán las
    * entidades registradas.
    *
    * @param gestor gestor de entidades del sistema
    */
   public FrmEmbarcacion(GestorEntidades gestor) {
       initComponents();
       
    System.out.println("SE ABRIÓ FrmEmbarcacion");

       this.gestor = gestor;
        cboCapitan.removeAllItems();

    cargarCapitanes();
    
       cboCapitan.setRenderer(new DefaultListCellRenderer() {

        @Override
        public Component getListCellRendererComponent(
                JList<?> list,
                Object value,
                int index,
                boolean isSelected,
                boolean cellHasFocus) {

            super.getListCellRendererComponent(
                    list,
                    value,
                    index,
                    isSelected,
                    cellHasFocus);

            if (value instanceof CapitanNave capitanNave) {
                setText(capitanNave.getNombre());
            }

            return this;
        }
    });
    
   }
   private void cargarCapitanes() {

    cboCapitan.removeAllItems();

    for (Registrable r : gestor.getEntidades()) {

        if (r instanceof CapitanNave capitan) {

            cboCapitan.addItem(capitan);

        }

    }

}
    /**
     * Limpia todos los campos del formulario.
     *
     * Se ejecuta después de registrar correctamente
     * un conductor para dejar el formulario listo
     * para un nuevo ingreso.
     */
    private void limpiarCampos() {

        ingreseIdentificadorNave.setText("");
        IngreseCapacidadNave.setText("");
        IngreseEstadoNave.setText("");
        IngreseTipoNave.setText("");
        IngreseEsloraNave.setText("");


    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        identificadorNave = new javax.swing.JLabel();
        ingreseIdentificadorNave = new javax.swing.JTextField();
        CapacidadNave = new javax.swing.JLabel();
        IngreseCapacidadNave = new javax.swing.JTextField();
        estadoNave = new javax.swing.JLabel();
        IngreseEstadoNave = new javax.swing.JTextField();
        responsableNave = new javax.swing.JLabel();
        tipoNave = new javax.swing.JLabel();
        IngreseTipoNave = new javax.swing.JTextField();
        eslora = new javax.swing.JLabel();
        IngreseEsloraNave = new javax.swing.JTextField();
        header = new javax.swing.JPanel();
        Titulo1 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        Footer = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        BtnVerRegistro = new javax.swing.JButton();
        cboCapitan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("RegistrarGuia"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(55, 55, 55));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 830));

        identificadorNave.setBackground(new java.awt.Color(55, 55, 55));
        identificadorNave.setForeground(new java.awt.Color(255, 255, 255));
        identificadorNave.setText("Identificador de la nave");

        ingreseIdentificadorNave.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ingreseIdentificadorNave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        ingreseIdentificadorNave.setPreferredSize(new java.awt.Dimension(400, 21));
        ingreseIdentificadorNave.addActionListener(this::ingreseIdentificadorNaveActionPerformed);

        CapacidadNave.setBackground(new java.awt.Color(55, 55, 55));
        CapacidadNave.setForeground(new java.awt.Color(255, 255, 255));
        CapacidadNave.setText("Capacidad de la nave");

        IngreseCapacidadNave.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseCapacidadNave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseCapacidadNave.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseCapacidadNave.addActionListener(this::IngreseCapacidadNaveActionPerformed);

        estadoNave.setBackground(new java.awt.Color(55, 55, 55));
        estadoNave.setForeground(new java.awt.Color(255, 255, 255));
        estadoNave.setText("Estado de la nave");

        IngreseEstadoNave.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseEstadoNave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseEstadoNave.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseEstadoNave.addActionListener(this::IngreseEstadoNaveActionPerformed);

        responsableNave.setBackground(new java.awt.Color(55, 55, 55));
        responsableNave.setForeground(new java.awt.Color(255, 255, 255));
        responsableNave.setText("Responsable");

        tipoNave.setBackground(new java.awt.Color(55, 55, 55));
        tipoNave.setForeground(new java.awt.Color(255, 255, 255));
        tipoNave.setText("Tipo");

        IngreseTipoNave.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseTipoNave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseTipoNave.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseTipoNave.addActionListener(this::IngreseTipoNaveActionPerformed);

        eslora.setBackground(new java.awt.Color(55, 55, 55));
        eslora.setForeground(new java.awt.Color(255, 255, 255));
        eslora.setText("Eslora");

        IngreseEsloraNave.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseEsloraNave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 193, 7)));
        IngreseEsloraNave.setPreferredSize(new java.awt.Dimension(400, 21));
        IngreseEsloraNave.addActionListener(this::IngreseEsloraNaveActionPerformed);

        header.setBackground(new java.awt.Color(90, 87, 87));
        header.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        header.setPreferredSize(new java.awt.Dimension(450, 65));

        Titulo1.setBackground(new java.awt.Color(55, 55, 55));
        Titulo1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setText("Ingrese los datos de la embarcacion");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(Titulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Titulo1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        footer.setBackground(new java.awt.Color(90, 87, 87));

        Footer.setBackground(new java.awt.Color(55, 55, 55));
        Footer.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Footer.setForeground(new java.awt.Color(255, 255, 255));
        Footer.setText("LLANQUIHUE TOUR APP ");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(Footer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Footer)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        BtnGuardar.setBackground(new java.awt.Color(70, 168, 61));
        BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setText("Guardar");
        BtnGuardar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnGuardar.addActionListener(this::BtnGuardarActionPerformed);

        BtnVolver.setBackground(new java.awt.Color(61, 98, 168));
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("Volver");
        BtnVolver.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnVolver.addActionListener(this::BtnVolverActionPerformed);

        BtnVerRegistro.setBackground(new java.awt.Color(255, 0, 0));
        BtnVerRegistro.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BtnVerRegistro.setForeground(new java.awt.Color(255, 255, 255));
        BtnVerRegistro.setText("Ver registro");
        BtnVerRegistro.setMaximumSize(new java.awt.Dimension(100, 30));
        BtnVerRegistro.setMinimumSize(new java.awt.Dimension(100, 30));
        BtnVerRegistro.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnVerRegistro.addActionListener(this::BtnVerRegistroActionPerformed);

        cboCapitan.addActionListener(this::cboCapitanActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
            .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eslora)
                    .addComponent(tipoNave)
                    .addComponent(IngreseTipoNave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(responsableNave)
                    .addComponent(estadoNave)
                    .addComponent(IngreseEstadoNave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IngreseCapacidadNave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(identificadorNave)
                    .addComponent(ingreseIdentificadorNave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnVerRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(IngreseEsloraNave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CapacidadNave, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCapitan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(identificadorNave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingreseIdentificadorNave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CapacidadNave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseCapacidadNave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(estadoNave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseEstadoNave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(responsableNave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboCapitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(tipoNave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseTipoNave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eslora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseEsloraNave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVerRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVerRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerRegistroActionPerformed
        FrmMostrarEntidades ventana = new FrmMostrarEntidades(gestor);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_BtnVerRegistroActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
    System.out.println("ENTRÉ AL BOTÓN");
          try {
   System.out.println("Inicio");

          CapitanNave capitan =
                  (CapitanNave) cboCapitan.getSelectedItem();
           System.out.println(
      "[" + IngreseCapacidadNave.getText() + "]"
    );

    System.out.println(
        "[" + IngreseEsloraNave.getText() + "]"
    );
    int capacidad =
            Integer.parseInt(IngreseCapacidadNave.getText());
      System.out.println("Capacidad: " + capacidad);
    double eslora =
            Double.parseDouble(IngreseEsloraNave.getText());

    System.out.println("Tipo: " + IngreseTipoNave.getText());
    System.out.println("Valida tipo: " + Validator.validarTipoNave(IngreseTipoNave.getText()));

    System.out.println("Eslora: " + eslora);
    System.out.println("Valida eslora: " + Validator.validarEslora(eslora));
    if (!Validator.validarIdentificador(
            ingreseIdentificadorNave.getText())) {

        throw new IllegalArgumentException(
                "Identificador inválido.");
    }

    if (!Validator.validarCapacidad(capacidad)) {

        throw new IllegalArgumentException(
                "Capacidad inválida.");
    }

    if (!Validator.validarEstado(
            IngreseEstadoNave.getText())) {

        throw new IllegalArgumentException(
                "Estado inválido.");
    }

    if (!Validator.validarTipoNave(
            IngreseTipoNave.getText())) {

        throw new IllegalArgumentException(
                "Tipo de embarcación inválido.");
    }

    if (!Validator.validarEslora(eslora)) {

        throw new IllegalArgumentException(
                "Eslora inválida.");
    }
          if (capitan == null) {

              throw new IllegalArgumentException(
                      "Debe seleccionar un capitán."
            );

        }
 
   Embarcacion embarcacion =
        new Embarcacion(
                gestor.generarNuevoId(),
                ingreseIdentificadorNave.getText(),
                capacidad,
                IngreseEstadoNave.getText(),
                capitan,
                IngreseTipoNave.getText(),
                eslora
        );

        gestor.agregarEntidad(embarcacion);

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Embarcación registrada correctamente."
        );

        limpiarCampos();

        } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );

    }
System.out.println(Validator.prueba());
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void IngreseTipoNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseTipoNaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseTipoNaveActionPerformed

    private void IngreseEstadoNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseEstadoNaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseEstadoNaveActionPerformed

    private void IngreseCapacidadNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseCapacidadNaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseCapacidadNaveActionPerformed

    private void ingreseIdentificadorNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreseIdentificadorNaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingreseIdentificadorNaveActionPerformed

    private void IngreseEsloraNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseEsloraNaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseEsloraNaveActionPerformed

    private void cboCapitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCapitanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCapitanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnVerRegistro;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel CapacidadNave;
    private javax.swing.JLabel Footer;
    private javax.swing.JTextField IngreseCapacidadNave;
    private javax.swing.JTextField IngreseEsloraNave;
    private javax.swing.JTextField IngreseEstadoNave;
    private javax.swing.JTextField IngreseTipoNave;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JComboBox<CapitanNave> cboCapitan;
    private javax.swing.JLabel eslora;
    private javax.swing.JLabel estadoNave;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel identificadorNave;
    private javax.swing.JTextField ingreseIdentificadorNave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel responsableNave;
    private javax.swing.JLabel tipoNave;
    // End of variables declaration//GEN-END:variables
}
