/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.llanquihueTourApp.ui;
import cl.llanquihueTourApp.data.GestorEntidades;

/**
 *
 * @author ADMIN
 */
public class FrmFront extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmFront.class.getName());
/**
 * Gestor central de entidades registradas en el sistema.
 *
 * Se comparte entre los distintos formularios para
 * almacenar y administrar las entidades creadas
 * durante la ejecución de la aplicación.
 */
private GestorEntidades gestor;

/**
 * Constructor del formulario principal.
 *
 * Inicializa los componentes gráficos y crea una
 * única instancia de GestorEntidades, la cual será
 * compartida con los demás formularios para registrar
 * y consultar las entidades del sistema.
 */
public FrmFront() {

    initComponents();

    gestor = new GestorEntidades();

    gestor.cargarDatos();

    System.out.println("FRONT: "
        + gestor.getEntidades().size());

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegistrarConductor = new javax.swing.JButton();
        MostarInformacion = new javax.swing.JButton();
        RegistrarServicioTuristico = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        RegistrarGuia = new javax.swing.JButton();
        registrarCapitan = new javax.swing.JButton();
        Slogan1 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        Slogan = new javax.swing.JLabel();
        titulo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        registrarAutomovil = new javax.swing.JButton();
        registrarEmbarcacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistrarConductor.setText("Registrar Conductor");
        RegistrarConductor.addActionListener(this::RegistrarConductorActionPerformed);
        jPanel1.add(RegistrarConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 310, 60));

        MostarInformacion.setText("Mostrar Información");
        MostarInformacion.addActionListener(this::MostarInformacionActionPerformed);
        jPanel1.add(MostarInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 310, 60));

        RegistrarServicioTuristico.setText("Registrar servicio turistico");
        RegistrarServicioTuristico.addActionListener(this::RegistrarServicioTuristicoActionPerformed);
        jPanel1.add(RegistrarServicioTuristico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 310, 60));

        Salir.setText("Salir");
        Salir.addActionListener(this::SalirActionPerformed);
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 670, 310, 60));

        RegistrarGuia.setText("Registrar Guia");
        RegistrarGuia.addActionListener(this::RegistrarGuiaActionPerformed);
        jPanel1.add(RegistrarGuia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 310, 60));

        registrarCapitan.setText("Registrar capitan");
        registrarCapitan.addActionListener(this::registrarCapitanActionPerformed);
        jPanel1.add(registrarCapitan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 310, 60));

        Slogan1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        Slogan1.setForeground(new java.awt.Color(255, 255, 255));
        Slogan1.setText("Registrete y se parte de nuestra empresa");
        jPanel1.add(Slogan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 390, -1));

        footer.setBackground(new java.awt.Color(90, 87, 87));

        Slogan.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Slogan.setForeground(new java.awt.Color(255, 255, 255));
        Slogan.setText("Llanquihue Tour Todos los derechos resevados 2026");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(Slogan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Slogan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 550, 90));

        titulo.setBackground(new java.awt.Color(90, 87, 87));
        titulo.setPreferredSize(new java.awt.Dimension(550, 60));

        Titulo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("LLANQUIHUE TOUR APP");

        javax.swing.GroupLayout tituloLayout = new javax.swing.GroupLayout(titulo);
        titulo.setLayout(tituloLayout);
        tituloLayout.setHorizontalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tituloLayout.setVerticalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 560, 70));

        registrarAutomovil.setText("Registrar Automovil");
        registrarAutomovil.addActionListener(this::registrarAutomovilActionPerformed);
        jPanel1.add(registrarAutomovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 310, 60));

        registrarEmbarcacion.setText("Registrar Embarcación");
        registrarEmbarcacion.addActionListener(this::registrarEmbarcacionActionPerformed);
        jPanel1.add(registrarEmbarcacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 310, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre el formulario de registro de conductores.
     *
     * @param evt evento generado al presionar el botón
    **
     * Muestra todas las entidades registradas en el sistema.
     *
     * @param evt evento generado al presionar el botón
     */
    private void MostarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostarInformacionActionPerformed
        FrmMostrarEntidades ventana = new FrmMostrarEntidades(gestor);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_MostarInformacionActionPerformed

    private void RegistrarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarConductorActionPerformed
        FrmConductor ventana = new FrmConductor(gestor);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_RegistrarConductorActionPerformed

    private void RegistrarServicioTuristicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarServicioTuristicoActionPerformed
        FrmServicioTuristico ventana =
        new FrmServicioTuristico(gestor);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_RegistrarServicioTuristicoActionPerformed

    private void RegistrarGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarGuiaActionPerformed
        FrmGuia ventana = new FrmGuia(gestor);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_RegistrarGuiaActionPerformed

    private void registrarCapitanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarCapitanActionPerformed
           FrmCapitanNave ventana = new FrmCapitanNave(gestor);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_registrarCapitanActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
           int opcion = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Desea salir de la aplicación?",
            "Confirmar salida",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_SalirActionPerformed

    private void registrarAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarAutomovilActionPerformed
        FrmAutomovil ventana = new FrmAutomovil(gestor);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_registrarAutomovilActionPerformed

    private void registrarEmbarcacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEmbarcacionActionPerformed
        FrmEmbarcacion ventana = new FrmEmbarcacion(gestor);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_registrarEmbarcacionActionPerformed
   
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MostarInformacion;
    private javax.swing.JButton RegistrarConductor;
    private javax.swing.JButton RegistrarGuia;
    private javax.swing.JButton RegistrarServicioTuristico;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Slogan;
    private javax.swing.JLabel Slogan1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registrarAutomovil;
    private javax.swing.JButton registrarCapitan;
    private javax.swing.JButton registrarEmbarcacion;
    private javax.swing.JPanel titulo;
    // End of variables declaration//GEN-END:variables
}
