/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.llanquihueTourApp.ui;
import cl.llanquihueTourApp.data.GestorEntidades;
import cl.llanquihueTourApp.model.*;
 
/**
 *
 * @author ADMIN
 */
public class FrmServicioTuristico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmServicioTuristico.class.getName());

      /**
    * Gestor encargado de administrar las entidades
    * registradas en el sistema.
    *
    * Se utiliza para agregar nuevos conductores y
    * generar automáticamente su identificador.
    */
    private GestorEntidades gestor;
    /**
    * Crea el formulario de registro de conductores.
    *
    * Inicializa los componentes gráficos y recibe
    * el gestor compartido donde se almacenarán las
    * entidades registradas.
    *
    * @param gestor gestor de entidades del sistema
    */
   public FrmServicioTuristico(GestorEntidades gestor) {
       initComponents();


    this.gestor = gestor;

    cargarGuias();
    cargarTransportes();

    CmbTipoServicio.removeAllItems();


    CmbTipoServicio.addItem("Paseo Lacustre");
    CmbTipoServicio.addItem("Ruta Gastronómica");
    CmbTipoServicio.addItem("Excursión Cultural");


    CmbTipoServicio.setSelectedIndex(0);


    actualizarCampos();


}
    
   private void cargarGuias() {

        cmbGuia.removeAllItems();

           for (Registrable r : gestor.getEntidades()) {

            if (r instanceof Guia guia) {

                cmbGuia.addItem(guia.getNombre());

            }

        }

    }
    private void cargarTransportes() {

        cmbTransporte.removeAllItems();

        for (Registrable r : gestor.getEntidades()) {

            if (r instanceof Transporte transporte) {

                cmbTransporte.addItem(transporte.getIdentificador());

            }
        }
   }
   private void actualizarCampos() {

    if (CmbTipoServicio.getSelectedItem() == null) {
          return;
      }

      String tipo = CmbTipoServicio.getSelectedItem().toString();

      switch (tipo) {

            case "Paseo Lacustre":

                lblDato1.setText("Lago");
                lblDato2.setText("Tipo de recorrido");
                lblDato3.setText("Tipo de embarcación");

                break;


            case "Ruta Gastronómica":

                lblDato1.setText("Restaurante");
                lblDato2.setText("Tipo gastronomía");
                lblDato3.setText("Cantidad de paradas");

                break;


            case "Excursión Cultural":

                lblDato1.setText("Lugar cultural");
                lblDato2.setText("Tipo patrimonio");
                lblDato3.setText("Entrada incluida");

                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        IngreseNombre = new javax.swing.JTextField();
        Descripcion = new javax.swing.JLabel();
        IngreseDescripcion = new javax.swing.JTextField();
        Duracion = new javax.swing.JLabel();
        IngreseDuracion = new javax.swing.JTextField();
        Precio = new javax.swing.JLabel();
        IngresePrecio = new javax.swing.JTextField();
        TipoServicio = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        VerRegistro = new javax.swing.JButton();
        CmbTipoServicio = new javax.swing.JComboBox<>();
        lblDato1 = new javax.swing.JLabel();
        TxtDato1 = new javax.swing.JTextField();
        lblDato2 = new javax.swing.JLabel();
        TxtDato2 = new javax.swing.JTextField();
        lblDato3 = new javax.swing.JLabel();
        TxtDato3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Transporte = new javax.swing.JLabel();
        cmbGuia = new javax.swing.JComboBox<>();
        cmbTransporte = new javax.swing.JComboBox<>();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 55, 55));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        Header.setBackground(new java.awt.Color(90, 87, 87));

        Titulo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Registrar servicio turistico");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Titulo)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(90, 87, 87));
        jPanel2.setPreferredSize(new java.awt.Dimension(410, 65));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LLANQUIHUE TOUR APP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Nombre");

        IngreseNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        IngreseNombre.addActionListener(this::IngreseNombreActionPerformed);

        Descripcion.setForeground(new java.awt.Color(255, 255, 255));
        Descripcion.setText("Descripción");

        IngreseDescripcion.addActionListener(this::IngreseDescripcionActionPerformed);

        Duracion.setForeground(new java.awt.Color(255, 255, 255));
        Duracion.setText("Duracion");

        IngreseDuracion.addActionListener(this::IngreseDuracionActionPerformed);

        Precio.setForeground(new java.awt.Color(255, 255, 255));
        Precio.setText("Precio");

        IngresePrecio.addActionListener(this::IngresePrecioActionPerformed);

        TipoServicio.setForeground(new java.awt.Color(255, 255, 255));
        TipoServicio.setText("Tipo de servicio");

        Guardar.setBackground(new java.awt.Color(70, 168, 61));
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");
        Guardar.setPreferredSize(new java.awt.Dimension(100, 30));
        Guardar.addActionListener(this::GuardarActionPerformed);

        Volver.setBackground(new java.awt.Color(61, 98, 168));
        Volver.setForeground(new java.awt.Color(255, 255, 255));
        Volver.setText("Volver");
        Volver.setPreferredSize(new java.awt.Dimension(100, 30));
        Volver.addActionListener(this::VolverActionPerformed);

        VerRegistro.setBackground(new java.awt.Color(255, 0, 0));
        VerRegistro.setForeground(new java.awt.Color(255, 255, 255));
        VerRegistro.setText("Ver registro");
        VerRegistro.setMaximumSize(new java.awt.Dimension(100, 30));
        VerRegistro.setMinimumSize(new java.awt.Dimension(100, 30));
        VerRegistro.addActionListener(this::VerRegistroActionPerformed);

        CmbTipoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbTipoServicio.addActionListener(this::CmbTipoServicioActionPerformed);

        lblDato1.setForeground(new java.awt.Color(255, 255, 255));
        lblDato1.setText("Dato1");

        TxtDato1.addActionListener(this::TxtDato1ActionPerformed);

        lblDato2.setForeground(new java.awt.Color(255, 255, 255));
        lblDato2.setText("Dato 2");

        TxtDato2.addActionListener(this::TxtDato2ActionPerformed);

        lblDato3.setForeground(new java.awt.Color(255, 255, 255));
        lblDato3.setText("Dato 3");

        TxtDato3.addActionListener(this::TxtDato3ActionPerformed);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Guia");

        Transporte.setForeground(new java.awt.Color(255, 255, 255));
        Transporte.setText("Automovil");

        cmbGuia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGuia.addActionListener(this::cmbGuiaActionPerformed);

        cmbTransporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTransporte.addActionListener(this::cmbTransporteActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre)
                    .addComponent(Descripcion)
                    .addComponent(IngreseDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Duracion)
                    .addComponent(IngreseDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Precio)
                    .addComponent(IngreseNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IngresePrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDato1)
                            .addComponent(lblDato2)
                            .addComponent(TxtDato2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDato3)
                            .addComponent(TxtDato3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TipoServicio)
                                .addGap(29, 29, 29)
                                .addComponent(CmbTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TxtDato1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(Transporte))
                            .addGap(55, 55, 55)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbGuia, 0, 281, Short.MAX_VALUE)
                                .addComponent(cmbTransporte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(8, 8, 8))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54)
                            .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46)
                            .addComponent(VerRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Descripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Duracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngreseDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Precio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresePrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Transporte)))
                    .addComponent(cmbGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmbTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoServicio))
                .addGap(19, 19, 19)
                .addComponent(lblDato1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDato1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDato2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDato2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDato3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDato3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VerRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngreseNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseNombreActionPerformed

    private void IngreseDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseDescripcionActionPerformed

    private void IngreseDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseDuracionActionPerformed

    private void IngresePrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresePrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresePrecioActionPerformed

    private void CmbTipoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbTipoServicioActionPerformed
           actualizarCampos();
    }//GEN-LAST:event_CmbTipoServicioActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
             
  try {

        int id = gestor.generarNuevoId();

        String nombre = IngreseNombre.getText();
        String descripcion = IngreseDescripcion.getText();
        String duracion = IngreseDuracion.getText();
        double precio = Double.parseDouble(IngresePrecio.getText());

        String lago = TxtDato1.getText();
        String recorrido = TxtDato2.getText();
        String embarcacion = TxtDato3.getText();
        Guia guia = (Guia) cmbGuia.getSelectedItem();

        Transporte transporte =
                (Transporte) cmbTransporte.getSelectedItem();
   

        PaseoLacustre paseo = new PaseoLacustre(
                id,
                nombre,
                descripcion,
                duracion,
                precio,
                guia,
                transporte,
                lago,
                recorrido,
                embarcacion
        );

        gestor.agregarEntidad(paseo);

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Servicio registrado correctamente."
        );


    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                e.getMessage()
            );

        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
         this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void VerRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerRegistroActionPerformed
          FrmMostrarEntidades ventana = new FrmMostrarEntidades(gestor);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_VerRegistroActionPerformed

    private void TxtDato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDato1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDato1ActionPerformed

    private void TxtDato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDato2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDato2ActionPerformed

    private void TxtDato3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDato3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDato3ActionPerformed

    private void cmbGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGuiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGuiaActionPerformed

    private void cmbTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTransporteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbTipoServicio;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Duracion;
    private javax.swing.JButton Guardar;
    private javax.swing.JPanel Header;
    private javax.swing.JTextField IngreseDescripcion;
    private javax.swing.JTextField IngreseDuracion;
    private javax.swing.JTextField IngreseNombre;
    private javax.swing.JTextField IngresePrecio;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel TipoServicio;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Transporte;
    private javax.swing.JTextField TxtDato1;
    private javax.swing.JTextField TxtDato2;
    private javax.swing.JTextField TxtDato3;
    private javax.swing.JButton VerRegistro;
    private javax.swing.JButton Volver;
    private javax.swing.JComboBox<String> cmbGuia;
    private javax.swing.JComboBox<String> cmbTransporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblDato1;
    private javax.swing.JLabel lblDato2;
    private javax.swing.JLabel lblDato3;
    // End of variables declaration//GEN-END:variables
}
